1. Forward Propagation

In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# Dataset
X = np.array([[2],[4],[6],[8],[10]])
y = np.array([0,0,1,1,1])

# Model
model = Sequential([
    Dense(8, activation='relu', input_shape=(1,)),
    Dense(1, activation='sigmoid')
])

# Compile
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Train
model.fit(X, y, epochs=100, verbose=0)

# Forward Propagation (Prediction)
prediction = model.predict(np.array([[7]]))

print("Probability:", prediction[0][0])

if prediction[0][0] >= 0.5:
    print("Prediction: PASS")
else:
    print("Prediction: FAIL")

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step
Probability: 0.6791118
Prediction: PASS


2. Mean Squared Error (MSE)

In [2]:
from sklearn.metrics import mean_squared_error

actual = [10,20,30]
predicted = [12,18,35]

loss = mean_squared_error(actual, predicted)

print("Mean Squared Error:", loss)

Mean Squared Error: 11.0


3. Binary Cross Entropy

In [3]:
from sklearn.metrics import log_loss

actual = [1,0,1]
prediction = [0.9,0.2,0.8]

loss = log_loss(actual, prediction)

print("Binary Cross Entropy:", loss)

Binary Cross Entropy: 0.18388253942874858


4. Categorical Cross Entropy

In [4]:
import tensorflow as tf
from tensorflow.keras.losses import CategoricalCrossentropy
import numpy as np

# One-hot encoded labels
actual = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])

prediction = np.array([
    [0.8,0.1,0.1],
    [0.2,0.7,0.1],
    [0.1,0.2,0.7]
])

loss_fn = CategoricalCrossentropy()

loss = loss_fn(actual, prediction)

print("Categorical Cross Entropy:", loss.numpy())

Categorical Cross Entropy: 0.3121645


5. Backward Propagation (Weight Update)

In [5]:
weight = 2.5
gradient = 0.8
learning_rate = 0.1

new_weight = weight - learning_rate * gradient

print("Old Weight:", weight)
print("Gradient:", gradient)
print("New Weight:", new_weight)

Old Weight: 2.5
Gradient: 0.8
New Weight: 2.42


6. Gradient Descent

In [6]:
weight = 5
gradient = 3
learning_rate = 0.1

for epoch in range(5):
    weight = weight - learning_rate * gradient
    print(f"Epoch {epoch+1}: Weight = {weight:.2f}")

Epoch 1: Weight = 4.70
Epoch 2: Weight = 4.40
Epoch 3: Weight = 4.10
Epoch 4: Weight = 3.80
Epoch 5: Weight = 3.50


7. Complete Neural Network (TensorFlow/Keras)

In [7]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# Dataset
X = np.array([[2],[4],[6],[8],[10]])
y = np.array([0,0,1,1,1])

# Build Model
model = Sequential([
    Dense(8, activation='relu', input_shape=(1,)),
    Dense(4, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Train
model.fit(X, y, epochs=100, verbose=1)

# Evaluate
loss, accuracy = model.evaluate(X, y, verbose=0)

print("Loss:", loss)
print("Accuracy:", accuracy)

# Predict
test = np.array([[3],[5],[7],[9]])

predictions = model.predict(test)

for x, p in zip(test, predictions):
    if p[0] >= 0.5:
        result = "PASS"
    else:
        result = "FAIL"

    print(f"Study Hours = {x[0]}, Probability = {p[0]:.4f}, Prediction = {result}")

Epoch 1/100


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.6000 - loss: 0.5508
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6000 - loss: 0.5480
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6000 - loss: 0.5454
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.6000 - loss: 0.5428
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6000 - loss: 0.5404
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6000 - loss: 0.5382
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6000 - loss: 0.5361
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6000 - loss: 0.5342
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.6000 - loss: 0.5325
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.6000 - loss: 0.5309
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.6000 - loss: 0.5295
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6000 - loss: 0.5282
Epo

8. Model Summary

In [8]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 8)              │            16 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 4)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 173 (696.00 B)

 Trainable params: 57 (228.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 116 (468.00 B)

9. Display Weights and Biases

In [9]:
for i, layer in enumerate(model.layers):

    weights, biases = layer.get_weights()

    print(f"\nLayer {i+1}")

    print("Weights")
    print(weights)

    print("Biases")
    print(biases)


Layer 1
Weights
[[-0.62064993  0.3882617   0.49346757  0.75997084  0.16497464 -0.6890615
   0.37393406 -0.45613584]]
Biases
[ 0.         -0.09242265 -0.09259949  0.09533635 -0.09324592  0.
 -0.09250363  0.        ]

Layer 2
Weights
[[ 0.3991751  -0.07023841 -0.65067434  0.46074718]
 [ 0.01619612  0.39522952  0.2676506   0.2649828 ]
 [ 0.168264   -0.55168587  0.44514453  0.42697984]
 [ 0.43474153 -0.70189166 -0.3325347  -0.32409284]
 [ 0.31079286 -0.21800458  0.5844003   0.33918613]
 [-0.66749024  0.18723112 -0.3539708  -0.4391282 ]
 [ 0.53161556 -0.1395207   0.32788414  0.19967586]
 [-0.1369009   0.23646235 -0.12707663  0.19348335]]
Biases
[-0.0911872   0.         -0.09316192  0.09309341]

Layer 3
Weights
[[ 0.07126178]
 [ 0.59612834]
 [ 0.86274457]
 [-0.23818575]]
Biases
[-0.09290363]


10. Predict for a New Student

In [10]:
study_hours = 3

prediction = model.predict(np.array([[study_hours]]))

print("Study Hours:", study_hours)
print("Probability:", prediction[0][0])

if prediction[0][0] >= 0.5:
    print("Final Prediction: PASS")
else:
    print("Final Prediction: FAIL")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step
Study Hours: 3
Probability: 0.60429305
Final Prediction: PASS
